### PR TITLE
refactor: codebase

### PR DESCRIPTION
**Pull request by devofficer**

### CODE REVIEW

**Comment by greenlucid** [comment]
Neither the name of this PR or the last commit are informative. All refactors are "cleaning messy code". What have you refactored specifically? If not in the PR (because, it's a big refactor PR), then you should've written it in the commit. And, if you changed too many things in the commit, then you should've divided it in multiple smaller refactors

You've done good changes, but they're hard to see because the folder structure created a lot of noise. You should've separated these commits (or, at least write that they happened):
- changing folder structure
- `<StyledSpin/>` -> `<Loading/>`
- removing PropTypes
- `hooks/useNetworkEnvVariable` -> `utils/getNetworkEnvVariable`
- split `bootstrap/app.js` into `app.jsx` and `app-router.jsx`
- `Items` and `ItemsDetailsRouter` no longer receive props 

I think `.js` -> `.jsx` won't break anything so that's fine

**Comment by greenlucid** [comment]
Can you do the `/tcr/${tcrAddress}?chainId=1` ->  `/tcr/${chainId}/${tcrAddress}` change in this PR?

**Comment by greenlucid** [comment]
Clicking the avatar in the top right corner, then "Switch to Mainnet" or "Switch to xDAI" returns an error, please fix it before.
MetaMask and ethers log an error when you try clicking it, that may be a hint

**Comment by greenlucid** [comment]
You're only checking for the existence of a lregistry, but you're not checking classic registries
you should add a query for `registry` in the `TCR_EXISTENCE_TEST`, and handle the possibility of the registry being classic

**Comment by devofficer** [comment]
> TCR_EXISTENCE_TEST



> You're only checking for the existence of a lregistry, but you're not checking classic registries you should add a query for `registry` in the `TCR_EXISTENCE_TEST`, and handle the possibility of the registry being classic

I see your points.

**Pull request merged**
